# Generated by Django 5.1.1 on 2024-10-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_studentanswer_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='student_id',
            new_name='studen_id',
        ),
    ]
