# Generated by Django 5.1 on 2024-10-16 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_rename_submission_time_quizresult_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_questions',
            field=models.IntegerField(),
        ),
    ]
