# Generated by Django 5.1.2 on 2024-10-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_question_category_question_subtopic_and_more'),
        ('quiz', '0015_all_questions'),
    ]

    operations = [
    ]
