# Generated by Django 5.1.2 on 2024-10-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_questiongen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongen',
            name='subtopic',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questiongen',
            name='topic',
            field=models.TextField(),
        ),
    ]
