# Generated by Django 5.1.1 on 2024-10-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_bio_profile_user_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='studen_id',
            new_name='student_id',
        ),
    ]
