# Generated by Django 5.1.2 on 2024-10-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_student_id_profile_studen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_images/user.jpg', null=True, upload_to='profile_images', verbose_name='Profile Pic'),
        ),
    ]
