# Generated by Django 5.1.1 on 2024-10-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_qustion_text_question_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='incoorect_answers',
            new_name='incorrect_answers',
        ),
        migrations.RenameField(
            model_name='quizresult',
            old_name='submsission_time',
            new_name='submission_time',
        ),
    ]
