# Generated by Django 5.1.1 on 2024-10-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_studentanswer_score_alter_studentanswer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='student_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
