# Generated by Django 5.1.1 on 2024-10-13 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_duration_quiz_total_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='submission_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
