# Generated by Django 5.1 on 2024-10-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_studentanswer_is_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('difficulty', models.IntegerField(default=1)),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('correct_option', models.TextField()),
            ],
        ),
    ]
