# Generated by Django 5.1 on 2024-10-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_allquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllQuestion',
        ),
    ]
