# Generated by Django 5.1.2 on 2024-10-24 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_merge_20241023_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('topic', models.CharField(max_length=255)),
                ('subtopic', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField(default=1)),
                ('CLO', models.IntegerField(default=1)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('FIB', 'Fill in the Blank')], max_length=3)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.category')),
            ],
        ),
    ]
