# Generated by Django 5.1.2 on 2024-10-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subtopic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
