# Generated by Django 5.1.2 on 2024-10-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_alter_question_subtopic_alter_question_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_questions',
        ),
    ]
