# Generated by Django 5.1.3 on 2024-11-06 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_delete_all_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FullStudentAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('option_1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_1', to='quiz.option')),
                ('option_2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_2', to='quiz.option')),
                ('option_3', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_3', to='quiz.option')),
                ('option_4', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_4', to='quiz.option')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('quiz_result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizresult')),
                ('selected_option', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.option')),
            ],
        ),
    ]
