# Generated by Django 5.1.2 on 2024-10-29 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allClass', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='myclass',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ClassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('myclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_requests', to='allClass.myclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'myclass')},
            },
        ),
    ]
